name: flutter_dddbf
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.12.0
  flutter_bloc: ^6.0.6
  json_serializable: ^3.5.0
  injectable: ^1.0.5
  get_it: ^5.0.1
  cupertino_icons: ^1.0.0
  firebase_core: "0.5.0+1"
  cloud_firestore: "^0.14.1+3"
  firebase_auth: ^0.18.1+2
  firebase_messaging: ^7.0.3
  firebase_analytics: ^6.0.2
  shared_preferences: ^0.5.12
  auto_route: ^0.6.9
  dartz: ^0.9.2
  flutter_spinkit: "^4.1.2"

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.11.6
  build_runner: ^1.10.2
  auto_route_generator: ^0.6.9
  injectable_generator: ^1.0.5
  flutter_hooks: ^0.14.1

flutter:
  uses-material-design: true
  # assets:
  #   - assets/example.png
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
